MVCtest/Models/ErrorViewModel.cs
namespace MVCtest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCtest/Models/SignupModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVCtest.Models
{
    public class SignupModel
    {
        [Required]
        [DataType(DataType.EmailAddress,ErrorMessage ="Email is missing or invalid")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password, ErrorMessage ="Incorrect or missing password")]
        public string Password { get; set; }

    }
}

MVCtest/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVCtest.Models;

namespace MVCtest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCtest/Controllers/identityController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations.Internal;
using MVCtest.Models;

namespace MVCtest.Controllers
{
    public class IdentityController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;

        public IdentityController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> signUp()
        {
            var model = new SignupModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> signUp(SignupModel model)
        {
            if (ModelState.IsValid) 
            { 
                if((await _userManager.FindByEmailAsync(model.Email)) != null) 
                {
                    var user = new IdentityUser
                    {
                        Email = model.Email,
                        UserName = model.Email
                    };
                    var result = await _userManager.CreateAsync(user, model.Password);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Signin");
                    }

                    ModelState.AddModelError("Signup", string.Join(", ", result.Errors.Select(x => x.Description)));

                }
            
            }


            return View(model);
        }

        public async Task<IActionResult> signIn()
        {
            return View();
        }

        public async Task<IActionResult> AccessDenied()
        {
            return View();
        }

    }
}

MVCtest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model SignupModel

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

<section id="Logins">

    <div class="container-md">
        <div class="text-center">
            <h2>Login to database</h2>
            <p class="lead text-muted">User login</p>
        </div>


        <div class="row.my-5.g-5.justify-content-around.allign-items-centre">
            <div class="col-6.col-lg">
                <p></p>
            </div>

            @* accordion *@
            <div class="accordion" id="logins">
          
                <div class="accordion-item">
                    
                    <h2 class="accordion-header" id="heading-1">

                        <button class="accordion-button d-block text-center" type="button" data-bs-toggle="collapse"
                        data-bs-target="#loginDetails" aria-expanded="true" aria-controls="loginDetails">User Login
                        </button>

                    </h2> 

                    <div id="loginDetails" class="accordion-collapse collapse show" aria-labelledby="heading-1" data-bs-parent="logins" > 

                        <div class="accordion-body">

                            <form asp-controller="Identity" asp-action="Signup" method="post">

                                <div class="form-group col-4">
                                    <label asp-for="Email">Email: </label>
                                    <input type="text" asp-for="Email" class="form-control" /> 

                                </div>

                                <div class="form-group col-4">
                                    <label asp-for="Password">Password: </label>
                                    <input type="text" asp-for="Password" class="form-control" />

                                </div>

                                <button type="submit" class="btn btn-primary">Signup!</button>

                            </form>

                        </div>

                    </div>
                    
                </div>
                @* end of accordion item One *@
                <div class="accordion-item">

                    <h2 class="accordion-header" id="heading-2">

                        <button class="accordion-button d-block text-center" type="button" data-bs-toggle="collapse"
                                data-bs-target="#adminLoginDetails" aria-expanded="true" aria-controls="adminLoginDetails">
                            Admin Login
                        </button>

                    </h2>

                    <div id="adminLoginDetails" class="accordion-collapse collapse" aria-labelledby="heading-2" data-bs-parent="logins">

                        <div class="accordion-body">

                            <p>
                                " Test Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                            </p>

                        </div>

                    </div>

                </div>


            </div>


        </div>
    </div>




</section>

MVCtest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCtest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCtest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCtest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVCtest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>